//------------------------------------------------------------------------------
// <auto-generated>
//	 Este código fue generado por una herramienta.
//	 Versión de runtime:4.0.30319.42000
//
//	 Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//	 se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKHOSTING.ERP.Resources {
	using System;
	using System.Reflection;
	
	
	/// <summary>
	///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
	/// </summary>
	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OKHOSTING.ERP.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Account.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_Account {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_Account", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Description.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_Account_Description {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_Account_Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a History.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_Account_History {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_Account_History", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_Account_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_Account_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Parent.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_Account_Parent {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_Account_Parent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Projections.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_Account_Projections {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_Account_Projections", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sub accounts.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_Account_SubAccounts {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_Account_SubAccounts", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Value.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_Account_Value {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_Account_Value", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Account projection.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_AccountProjection {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_AccountProjection", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Account.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_AccountProjection_Account {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_AccountProjection_Account", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Actual value.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_AccountProjection_ActualValue {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_AccountProjection_ActualValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Date.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_AccountProjection_Date {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_AccountProjection_Date", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Difference.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_AccountProjection_Difference {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_AccountProjection_Difference", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Projected value.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_AccountProjection_ProjectedValue {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_AccountProjection_ProjectedValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Account update.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_AccountUpdate {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_AccountUpdate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Account.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_AccountUpdate_Account {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_AccountUpdate_Account", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Date.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_AccountUpdate_Date {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_AccountUpdate_Date", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Updated value.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_AccountUpdate_UpdatedValue {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_AccountUpdate_UpdatedValue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Calculated account.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_CalculatedAccount {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_CalculatedAccount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Object calculated account.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_ObjectCalculatedAccount {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_ObjectCalculatedAccount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Periodic type calculated account.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_PeriodicTypeCalculatedAccount {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_PeriodicTypeCalculatedAccount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Date property.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_PeriodicTypeCalculatedAccount_DateProperty {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_PeriodicTypeCalculatedAccount_DateProperty", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Period lenght.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_PeriodicTypeCalculatedAccount_PeriodLenght {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_PeriodicTypeCalculatedAccount_PeriodLenght", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Period unit.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_PeriodicTypeCalculatedAccount_PeriodUnit {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_PeriodicTypeCalculatedAccount_PeriodUnit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Start.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_PeriodicTypeCalculatedAccount_Start {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_PeriodicTypeCalculatedAccount_Start", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Type calculated account.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_TypeCalculatedAccount {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_TypeCalculatedAccount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Evaluated type.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_TypeCalculatedAccount_EvaluatedType {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_TypeCalculatedAccount_EvaluatedType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Evaluation expression.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_TypeCalculatedAccount_EvaluationExpression {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_TypeCalculatedAccount_EvaluationExpression", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Evaluation filter.
		/// </summary>
		internal static string OKHOSTING_ERP_Accounting_TypeCalculatedAccount_EvaluationFilter {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Accounting_TypeCalculatedAccount_EvaluationFilter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Address.
		/// </summary>
		internal static string OKHOSTING_ERP_Address {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Address", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a City.
		/// </summary>
		internal static string OKHOSTING_ERP_Address_City {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Address_City", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Country.
		/// </summary>
		internal static string OKHOSTING_ERP_Address_Country {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Address_Country", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Fulll address.
		/// </summary>
		internal static string OKHOSTING_ERP_Address_FulllAddress {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Address_FulllAddress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Notes.
		/// </summary>
		internal static string OKHOSTING_ERP_Address_Notes {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Address_Notes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Number.
		/// </summary>
		internal static string OKHOSTING_ERP_Address_Number {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Address_Number", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a State.
		/// </summary>
		internal static string OKHOSTING_ERP_Address_State {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Address_State", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Street.
		/// </summary>
		internal static string OKHOSTING_ERP_Address_Street {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Address_Street", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Suburb.
		/// </summary>
		internal static string OKHOSTING_ERP_Address_Suburb {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Address_Suburb", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Zip code.
		/// </summary>
		internal static string OKHOSTING_ERP_Address_ZipCode {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Address_ZipCode", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Company.
		/// </summary>
		internal static string OKHOSTING_ERP_Company {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Addresses.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_Addresses {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_Addresses", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a All emails.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_AllEmails {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_AllEmails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a All telephones.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_AllTelephones {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_AllTelephones", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Commercial name.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_CommercialName {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_CommercialName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Contacts.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_Contacts {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_Contacts", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Email.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_Email {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_Email", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Email 2.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_Email2 {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_Email2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Federal tax id.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_FederalTaxID {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_FederalTaxID", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Legal name.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_LegalName {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_LegalName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Main address.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_MainAddress {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_MainAddress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Main contact.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_MainContact {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_MainContact", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Mobile telephone.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_MobileTelephone {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_MobileTelephone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Notes.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_Notes {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_Notes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Telephone.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_Telephone {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_Telephone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Telephone 2.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_Telephone2 {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_Telephone2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Url.
		/// </summary>
		internal static string OKHOSTING_ERP_Company_Url {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Company_Url", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Company address.
		/// </summary>
		internal static string OKHOSTING_ERP_CompanyAddress {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_CompanyAddress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Address type.
		/// </summary>
		internal static string OKHOSTING_ERP_CompanyAddress_AddressType {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_CompanyAddress_AddressType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Company.
		/// </summary>
		internal static string OKHOSTING_ERP_CompanyAddress_Company {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_CompanyAddress_Company", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Company address type.
		/// </summary>
		internal static string OKHOSTING_ERP_CompanyAddressType {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_CompanyAddressType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Billing.
		/// </summary>
		internal static string OKHOSTING_ERP_CompanyAddressType_Billing {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_CompanyAddressType_Billing", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Other.
		/// </summary>
		internal static string OKHOSTING_ERP_CompanyAddressType_Other {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_CompanyAddressType_Other", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Shipping.
		/// </summary>
		internal static string OKHOSTING_ERP_CompanyAddressType_Shipping {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_CompanyAddressType_Shipping", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Company contact.
		/// </summary>
		internal static string OKHOSTING_ERP_Employee {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Employee", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Company.
		/// </summary>
		internal static string OKHOSTING_ERP_Employee_Company {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Employee_Company", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Role.
		/// </summary>
		internal static string OKHOSTING_ERP_Employee_Role {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Employee_Role", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Configuration.
		/// </summary>
		internal static string OKHOSTING_ERP_Configuration {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Configuration", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Current.
		/// </summary>
		internal static string OKHOSTING_ERP_Configuration_Current {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Configuration_Current", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a My billing address.
		/// </summary>
		internal static string OKHOSTING_ERP_Configuration_MyBillingAddress {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Configuration_MyBillingAddress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a My company.
		/// </summary>
		internal static string OKHOSTING_ERP_Configuration_MyCompany {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Configuration_MyCompany", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a My main contact.
		/// </summary>
		internal static string OKHOSTING_ERP_Configuration_MyMainContact {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Configuration_MyMainContact", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a My shipping address.
		/// </summary>
		internal static string OKHOSTING_ERP_Configuration_MyShippingAddress {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Configuration_MyShippingAddress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Country.
		/// </summary>
		internal static string OKHOSTING_ERP_Country {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Country", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Currency.
		/// </summary>
		internal static string OKHOSTING_ERP_Country_Currency {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Country_Currency", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Iso 2.
		/// </summary>
		internal static string OKHOSTING_ERP_Country_Iso2 {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Country_Iso2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Iso 3.
		/// </summary>
		internal static string OKHOSTING_ERP_Country_Iso3 {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Country_Iso3", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Country_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Country_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Numeric code.
		/// </summary>
		internal static string OKHOSTING_ERP_Country_NumericCode {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Country_NumericCode", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Phone code.
		/// </summary>
		internal static string OKHOSTING_ERP_Country_PhoneCode {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Country_PhoneCode", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Currency.
		/// </summary>
		internal static string OKHOSTING_ERP_Currency {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Currency", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Alphabetic code.
		/// </summary>
		internal static string OKHOSTING_ERP_Currency_AlphabeticCode {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Currency_AlphabeticCode", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Currency_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Currency_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Rate.
		/// </summary>
		internal static string OKHOSTING_ERP_Currency_Rate {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Currency_Rate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Symbol after.
		/// </summary>
		internal static string OKHOSTING_ERP_Currency_SymbolAfter {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Currency_SymbolAfter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Symbol before.
		/// </summary>
		internal static string OKHOSTING_ERP_Currency_SymbolBefore {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Currency_SymbolBefore", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Customer.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Active.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_Active {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_Active", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Balance.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_Balance {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_Balance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Category.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_Category {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_Category", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Currency.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_Currency {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_Currency", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a First sale date.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_FirstSaleDate {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_FirstSaleDate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a How did you find us.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_HowDidYouFindUs {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_HowDidYouFindUs", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Last sale date.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_LastSaleDate {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_LastSaleDate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Quotes.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_Quotes {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_Quotes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Registered since.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_RegisteredSince {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_RegisteredSince", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sales.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_Sales {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_Sales", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sales person.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_SalesPerson {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_SalesPerson", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sold products.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_SoldProducts {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_SoldProducts", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sold products string.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_SoldProductsString {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_SoldProductsString", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Total sales.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_TotalSales {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_TotalSales", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Total sold.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Customer_TotalSold {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Customer_TotalSold", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Customer category.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerCategory {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerCategory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Customers.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerCategory_Customers {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerCategory_Customers", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Description.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerCategory_Description {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerCategory_Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerCategory_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerCategory_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Price adjustment.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerCategory_PriceAdjustment {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerCategory_PriceAdjustment", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Customer feedback.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerFeedback {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerFeedback", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Comment.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerFeedback_Comment {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerFeedback_Comment", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Customer.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerFeedback_Customer {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerFeedback_Customer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Date.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerFeedback_Date {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerFeedback_Date", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Employee.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerFeedback_Employee {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerFeedback_Employee", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Satisfaction level.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerFeedback_SatisfactionLevel {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerFeedback_SatisfactionLevel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Team.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_CustomerFeedback_Team {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_CustomerFeedback_Team", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Prospect.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Prospect {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Prospect", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Next call date.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Prospect_NextCallDate {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Prospect_NextCallDate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Potential sale ammount.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Prospect_PotentialSaleAmmount {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Prospect_PotentialSaleAmmount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Product of interest.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Prospect_ProductOfInterest {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Prospect_ProductOfInterest", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Registration date.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Prospect_RegistrationDate {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Prospect_RegistrationDate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sales person.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Prospect_SalesPerson {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Prospect_SalesPerson", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Source.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Prospect_Source {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Prospect_Source", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Status.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Prospect_Status {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Prospect_Status", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Prospect source.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_ProspectSource {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_ProspectSource", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_ProspectSource_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_ProspectSource_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Prospect status.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_ProspectStatus {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_ProspectStatus", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_ProspectStatus_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_ProspectStatus_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Pipe line order.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_ProspectStatus_PipeLineOrder {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_ProspectStatus_PipeLineOrder", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Quote.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Quote {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Quote", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Commission level.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Quote_CommissionLevel {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Quote_CommissionLevel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Customer.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Quote_Customer {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Quote_Customer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sales person.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Quote_SalesPerson {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Quote_SalesPerson", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sale.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Sale {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Sale", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Commission level.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Sale_CommissionLevel {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Sale_CommissionLevel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Customer.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Sale_Customer {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Sale_Customer", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sales person.
		/// </summary>
		internal static string OKHOSTING_ERP_Customers_Sale_SalesPerson {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Customers_Sale_SalesPerson", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Tax.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_Tax {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_Tax", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_Tax_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_Tax_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Rate.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_Tax_Rate {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_Tax_Rate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Tax agency.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_Tax_TaxAgency {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_Tax_TaxAgency", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Tax groups.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_Tax_TaxGroups {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_Tax_TaxGroups", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Tax agency.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_TaxAgency {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_TaxAgency", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Email.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_TaxAgency_Email {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_TaxAgency_Email", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Fax.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_TaxAgency_Fax {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_TaxAgency_Fax", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_TaxAgency_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_TaxAgency_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Notes.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_TaxAgency_Notes {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_TaxAgency_Notes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Telephone.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_TaxAgency_Telephone {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_TaxAgency_Telephone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Url.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_TaxAgency_Url {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_TaxAgency_Url", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Tax group.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_TaxGroup {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_TaxGroup", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_TaxGroup_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_TaxGroup_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Taxes.
		/// </summary>
		internal static string OKHOSTING_ERP_Finances_TaxGroup_Taxes {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Finances_TaxGroup_Taxes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Gender.
		/// </summary>
		internal static string OKHOSTING_ERP_Gender {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Gender", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Female.
		/// </summary>
		internal static string OKHOSTING_ERP_Gender_Female {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Gender_Female", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Male.
		/// </summary>
		internal static string OKHOSTING_ERP_Gender_Male {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Gender_Male", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Commission level.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_CommissionLevel {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_CommissionLevel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Commission.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_CommissionLevel_Commission {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_CommissionLevel_Commission", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_CommissionLevel_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_CommissionLevel_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Department.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Department {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Department", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Description.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Department_Description {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Department_Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Department_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Department_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Parent.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Department_Parent {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Department_Parent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Employee.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Employee {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Employee", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Active.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Employee_Active {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Employee_Active", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Enrollment date.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Employee_EnrollmentDate {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Employee_EnrollmentDate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Mail signature.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Employee_MailSignature {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Employee_MailSignature", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Role.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Employee_Role {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Employee_Role", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Salary.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Employee_Salary {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Employee_Salary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Salary type.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Employee_SalaryType {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Employee_SalaryType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Team.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Employee_Team {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Employee_Team", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Salary type.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_SalaryType {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_SalaryType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Per bi week.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_SalaryType_PerBiWeek {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_SalaryType_PerBiWeek", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Per day.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_SalaryType_PerDay {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_SalaryType_PerDay", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Per hour.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_SalaryType_PerHour {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_SalaryType_PerHour", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Per month.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_SalaryType_PerMonth {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_SalaryType_PerMonth", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Per week.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_SalaryType_PerWeek {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_SalaryType_PerWeek", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Per work.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_SalaryType_PerWork {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_SalaryType_PerWork", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sales person.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_SalesPerson {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_SalesPerson", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Comission.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_SalesPerson_Comission {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_SalesPerson_Comission", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Team.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Team {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Team", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Description.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Team_Description {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Team_Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Employees.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Team_Employees {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Team_Employees", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Team_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Team_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Parent.
		/// </summary>
		internal static string OKHOSTING_ERP_HR_Team_Parent {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_HR_Team_Parent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Invoice.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Aux id.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_AuxId {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_AuxId", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Balance.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_Balance {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_Balance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Category.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_Category {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_Category", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Date.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_Date {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_Date", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Invoice type.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_InvoiceType {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_InvoiceType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Items.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_Items {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_Items", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Notes.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_Notes {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_Notes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Paid.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_Paid {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_Paid", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Payments.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_Payments {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_Payments", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Subtotal.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_Subtotal {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_Subtotal", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Tax.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_Tax {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_Tax", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Total.
		/// </summary>
		internal static string OKHOSTING_ERP_Invoice_Total {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Invoice_Total", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Invoice category.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceCategory {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceCategory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Description.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceCategory_Description {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceCategory_Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceCategory_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceCategory_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Invoice item.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Description.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_Description {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Discount.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_Discount {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_Discount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Invoice.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_Invoice {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_Invoice", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Price.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_Price {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_Price", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Product.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_Product {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_Product", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Product instance.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_ProductInstance {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_ProductInstance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Quantity.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_Quantity {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_Quantity", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Subtotal.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_Subtotal {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_Subtotal", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Tax.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_Tax {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_Tax", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Taxes.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_Taxes {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_Taxes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Total.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItem_Total {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItem_Total", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Invoice item tax.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItemTax {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItemTax", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Amount.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItemTax_Amount {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItemTax_Amount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Item.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItemTax_Item {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItemTax_Item", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Tax.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceItemTax_Tax {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceItemTax_Tax", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Invoice payment.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoicePayment {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoicePayment", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Amount.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoicePayment_Amount {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoicePayment_Amount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Date.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoicePayment_Date {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoicePayment_Date", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Invoice.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoicePayment_Invoice {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoicePayment_Invoice", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Method.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoicePayment_Method {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoicePayment_Method", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Invoice type.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceType {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Purchase.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceType_Purchase {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceType_Purchase", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Quote.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceType_Quote {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceType_Quote", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sale.
		/// </summary>
		internal static string OKHOSTING_ERP_InvoiceType_Sale {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_InvoiceType_Sale", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Payment method.
		/// </summary>
		internal static string OKHOSTING_ERP_PaymentMethod {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_PaymentMethod", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_PaymentMethod_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_PaymentMethod_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Person.
		/// </summary>
		internal static string OKHOSTING_ERP_Person {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Age.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_Age {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_Age", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Alias.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_Alias {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_Alias", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Birth date.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_BirthDate {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_BirthDate", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Email.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_Email {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_Email", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Email 2.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_Email2 {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_Email2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Facebook account.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_FacebookAccount {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_FacebookAccount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a First name.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_FirstName {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_FirstName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Full name.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_FullName {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_FullName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Gender.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_Gender {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_Gender", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Last name.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_LastName {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_LastName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Mobile telephone.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_MobileTelephone {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_MobileTelephone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Notes.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_Notes {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_Notes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Prefix.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_Prefix {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_Prefix", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Telephone.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_Telephone {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_Telephone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Telephone 2.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_Telephone2 {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_Telephone2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Twitter account.
		/// </summary>
		internal static string OKHOSTING_ERP_Person_TwitterAccount {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Person_TwitterAccount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Package product.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_PackageProduct {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_PackageProduct", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Included products.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_PackageProduct_IncludedProducts {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_PackageProduct_IncludedProducts", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Package product included product.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_PackageProductIncludedProduct {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_PackageProductIncludedProduct", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Included product.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_PackageProductIncludedProduct_IncludedProduct {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_PackageProductIncludedProduct_IncludedProduct", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Package product.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_PackageProductIncludedProduct_PackageProduct {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_PackageProductIncludedProduct_PackageProduct", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Quantity.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_PackageProductIncludedProduct_Quantity {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_PackageProductIncludedProduct_Quantity", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Product.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Aux id.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_AuxId {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_AuxId", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Category.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_Category {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_Category", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Description.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_Description {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Has inventory.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_HasInventory {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_HasInventory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Preferred vendor.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_PreferredVendor {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_PreferredVendor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Preferred vendor item i d.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_PreferredVendorItemID {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_PreferredVendorItemID", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Price.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_Price {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_Price", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Product instance type.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_ProductInstanceType {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_ProductInstanceType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Purchase.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_Purchase {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_Purchase", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Purchase description.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_PurchaseDescription {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_PurchaseDescription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Purchase price.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_PurchasePrice {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_PurchasePrice", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Purchase taxes.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_PurchaseTaxes {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_PurchaseTaxes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sale.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_Sale {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_Sale", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sale taxes.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_SaleTaxes {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_SaleTaxes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Short name.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_ShortName {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_ShortName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Standard cost.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Product_StandardCost {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Product_StandardCost", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Product category.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductCategory {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductCategory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Description.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductCategory_Description {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductCategory_Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductCategory_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductCategory_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Parent.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductCategory_Parent {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductCategory_Parent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sub categories.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductCategory_SubCategories {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductCategory_SubCategories", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Product instance.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductInstance {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductInstance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Instance.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductInstance_Instance {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductInstance_Instance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Items.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductInstance_Items {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductInstance_Items", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductInstance_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductInstance_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Product.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductInstance_Product {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductInstance_Product", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Purchased to.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductInstance_PurchasedTo {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductInstance_PurchasedTo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Sold to.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_ProductInstance_SoldTo {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_ProductInstance_SoldTo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Subscription.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Subscription {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Subscription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Active.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Subscription_Active {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Subscription_Active", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Auto renew.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Subscription_AutoRenew {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Subscription_AutoRenew", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a End.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Subscription_End {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Subscription_End", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Grace period end.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Subscription_GracePeriodEnd {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Subscription_GracePeriodEnd", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Start.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Subscription_Start {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Subscription_Start", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Subscription product.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_SubscriptionProduct {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_SubscriptionProduct", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Grace period lenght.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_SubscriptionProduct_GracePeriodLenght {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_SubscriptionProduct_GracePeriodLenght", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Grace period unit.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_SubscriptionProduct_GracePeriodUnit {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_SubscriptionProduct_GracePeriodUnit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Subscription lenght.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_SubscriptionProduct_SubscriptionLenght {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_SubscriptionProduct_SubscriptionLenght", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Subscription unit.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_SubscriptionProduct_SubscriptionUnit {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_SubscriptionProduct_SubscriptionUnit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Warehouse.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Warehouse {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Warehouse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Address.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Warehouse_Address {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Warehouse_Address", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Manager.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Warehouse_Manager {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Warehouse_Manager", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Warehouse_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Warehouse_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Products.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Warehouse_Products {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Warehouse_Products", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Transactions.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_Warehouse_Transactions {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_Warehouse_Transactions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Warehouse product.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseProduct {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseProduct", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a On hand.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseProduct_OnHand {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseProduct_OnHand", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Product.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseProduct_Product {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseProduct_Product", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Reorder point.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseProduct_ReorderPoint {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseProduct_ReorderPoint", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Warehouse.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseProduct_Warehouse {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseProduct_Warehouse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Warehouse transaction.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseTransaction {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseTransaction", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Date.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseTransaction_Date {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseTransaction_Date", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Invoice.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseTransaction_Invoice {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseTransaction_Invoice", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Product.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseTransaction_Product {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseTransaction_Product", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Quantity.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseTransaction_Quantity {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseTransaction_Quantity", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Reason.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseTransaction_Reason {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseTransaction_Reason", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Warehouse.
		/// </summary>
		internal static string OKHOSTING_ERP_Production_WarehouseTransaction_Warehouse {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Production_WarehouseTransaction_Warehouse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Strings.
		/// </summary>
		internal static string OKHOSTING_ERP_Resources_Strings {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Resources_Strings", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Culture.
		/// </summary>
		internal static string OKHOSTING_ERP_Resources_Strings_Culture {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Resources_Strings_Culture", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a resource culture.
		/// </summary>
		internal static string OKHOSTING_ERP_Resources_Strings_resourceCulture {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Resources_Strings_resourceCulture", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a resource man.
		/// </summary>
		internal static string OKHOSTING_ERP_Resources_Strings_resourceMan {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Resources_Strings_resourceMan", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Resource manager.
		/// </summary>
		internal static string OKHOSTING_ERP_Resources_Strings_ResourceManager {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Resources_Strings_ResourceManager", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Time unit.
		/// </summary>
		internal static string OKHOSTING_ERP_TimeUnit {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_TimeUnit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Unit.
		/// </summary>
		internal static string OKHOSTING_ERP_Unit {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Unit", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Day.
		/// </summary>
		internal static string OKHOSTING_ERP_Unit_Day {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Unit_Day", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Hour.
		/// </summary>
		internal static string OKHOSTING_ERP_Unit_Hour {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Unit_Hour", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Minute.
		/// </summary>
		internal static string OKHOSTING_ERP_Unit_Minute {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Unit_Minute", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Month.
		/// </summary>
		internal static string OKHOSTING_ERP_Unit_Month {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Unit_Month", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Second.
		/// </summary>
		internal static string OKHOSTING_ERP_Unit_Second {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Unit_Second", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Week.
		/// </summary>
		internal static string OKHOSTING_ERP_Unit_Week {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Unit_Week", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Year.
		/// </summary>
		internal static string OKHOSTING_ERP_Unit_Year {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Unit_Year", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Purchase.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_Purchase {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_Purchase", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Vendor.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_Purchase_Vendor {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_Purchase_Vendor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Vendor.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_Vendor {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_Vendor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Balance.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_Vendor_Balance {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_Vendor_Balance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Category.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_Vendor_Category {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_Vendor_Category", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Currency.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_Vendor_Currency {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_Vendor_Currency", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Purchased products.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_Vendor_PurchasedProducts {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_Vendor_PurchasedProducts", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Purchases.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_Vendor_Purchases {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_Vendor_Purchases", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Vendor category.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_VendorCategory {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_VendorCategory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Description.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_VendorCategory_Description {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_VendorCategory_Description", resourceCulture);
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a Name.
		/// </summary>
		internal static string OKHOSTING_ERP_Vendors_VendorCategory_Name {
			get {
				return ResourceManager.GetString("OKHOSTING_ERP_Vendors_VendorCategory_Name", resourceCulture);
			}
		}
	}
}
